[package]
name = "gomoku-ai"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["gomoku-cli-pvp", "gomoku-core"]

[workspace.dependencies]
thiserror = "2"
gomoku-core = { path = "gomoku-core" }

[dependencies]
