[package]
name = "gomoku-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
figment = { workspace = true }
gomoku-core = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tch = { workspace = true }
